name: satisfaction_eventos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  http: ^1.6.0
  firebase_database: ^12.4.0
  bcrypt: ^1.2.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^6.0.0

# Configuração do Ícone do Aplicativo
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imagens/icone.png" 

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/logo_marca.png
    - assets/imagens/tecalli_tecnologia.png

