// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5zv5E4qCrIaTt4qT6o8mqtEvpdmxCyLo',
    appId: '1:671714407872:web:a7c5877bb0a63ff6840425',
    messagingSenderId: '671714407872',
    projectId: 'satisfaction-eventos',
    authDomain: 'satisfaction-eventos.firebaseapp.com',
    databaseURL: 'https://satisfaction-eventos-default-rtdb.firebaseio.com',
    storageBucket: 'satisfaction-eventos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCms6WNzZEeMUh_j_RD-wYXjQZLL9v1hIw',
    appId: '1:671714407872:android:0068d76320b58c36840425',
    messagingSenderId: '671714407872',
    projectId: 'satisfaction-eventos',
    databaseURL: 'https://satisfaction-eventos-default-rtdb.firebaseio.com',
    storageBucket: 'satisfaction-eventos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVgY9OYgmAuBYaruTaYFVOcu7iYBrIC0Y',
    appId: '1:671714407872:ios:12ba35887ab324c9840425',
    messagingSenderId: '671714407872',
    projectId: 'satisfaction-eventos',
    databaseURL: 'https://satisfaction-eventos-default-rtdb.firebaseio.com',
    storageBucket: 'satisfaction-eventos.firebasestorage.app',
    iosBundleId: 'com.example.satisfactionEventos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVgY9OYgmAuBYaruTaYFVOcu7iYBrIC0Y',
    appId: '1:671714407872:ios:12ba35887ab324c9840425',
    messagingSenderId: '671714407872',
    projectId: 'satisfaction-eventos',
    databaseURL: 'https://satisfaction-eventos-default-rtdb.firebaseio.com',
    storageBucket: 'satisfaction-eventos.firebasestorage.app',
    iosBundleId: 'com.example.satisfactionEventos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5zv5E4qCrIaTt4qT6o8mqtEvpdmxCyLo',
    appId: '1:671714407872:web:18cd4889e6d78bcd840425',
    messagingSenderId: '671714407872',
    projectId: 'satisfaction-eventos',
    authDomain: 'satisfaction-eventos.firebaseapp.com',
    databaseURL: 'https://satisfaction-eventos-default-rtdb.firebaseio.com',
    storageBucket: 'satisfaction-eventos.firebasestorage.app',
  );
}
